### ISSUE TITLE
intermittent failing specs for Curator::DigitalObjectFactoryService

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator#14]
We are seeing a handful of specs for `Curator::DigitalObjectFactoryService` failing intermittently. This seems to be due to the order in which associated `Curator::ControlledTerms` objects are created, which does not always match the order in the source `digital_object.json` fixture file.

Failed examples:
```
rspec ./spec/services/curator/digital_object_factory_service_spec.rb:159 # Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields resource_types sets the resource_type data
rspec ./spec/services/curator/digital_object_factory_service_spec.rb:182 # Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields languages sets the languages data
rspec ./spec/services/curator/digital_object_factory_service_spec.rb:231 # Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_names data
rspec ./spec/services/curator/digital_object_factory_service_spec.rb:222 # Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_topic data
rspec ./spec/services/curator/digital_object_factory_service_spec.rb:240 # Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_geos data
```
Failures:
```
  1) Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields resource_types sets the resource_type data
     Failure/Error: expect(resource_types[0].send(attr)).to eq desc_json['resource_types'][0][attr]
     
       expected: "Still Image"
            got: "Text"
     
       (compared using ==)
     # ./spec/services/curator/digital_object_factory_service_spec.rb:163:in `block (7 levels) in <top (required)>'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:162:in `each'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:162:in `block (6 levels) in <top (required)>'

  2) Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields languages sets the languages data
     Failure/Error: expect(languages[0].send(attr)).to eq desc_json['languages'][0][attr]
     
       expected: "Latin"
            got: "Italian"
     
       (compared using ==)
     # ./spec/services/curator/digital_object_factory_service_spec.rb:186:in `block (7 levels) in <top (required)>'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:185:in `each'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:185:in `block (6 levels) in <top (required)>'

  3) Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_names data
     Failure/Error: expect(subject_names[0].send(attr)).to eq desc_json['subject']['names'][0][attr]
     
       expected: "Zorn, Anders, 1860-1920"
            got: "Zorn, Emma, 1860-1942"
     
       (compared using ==)
     # ./spec/services/curator/digital_object_factory_service_spec.rb:235:in `block (7 levels) in <top (required)>'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:234:in `each'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:234:in `block (6 levels) in <top (required)>'

  4) Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_topic data
     Failure/Error: expect(subject_topics[0].send(attr)).to eq desc_json['subject']['topics'][0][attr]
     
       expected: "Hurricanes"
            got: "Babies"
     
       (compared using ==)
     # ./spec/services/curator/digital_object_factory_service_spec.rb:226:in `block (7 levels) in <top (required)>'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:225:in `each'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:225:in `block (6 levels) in <top (required)>'

  5) Curator::DigitalObjectFactoryService#call descriptive metastream controlled term fields subject sets the subject_geos data
     Failure/Error: expect(subject_geos[0].send(attr)).to eq desc_json['subject']['geos'][0][attr]
     
       expected: "Piacenza"
            got: "Lucy Vincent Beach"
     
       (compared using ==)
     # ./spec/services/curator/digital_object_factory_service_spec.rb:244:in `block (7 levels) in <top (required)>'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:243:in `each'
     # ./spec/services/curator/digital_object_factory_service_spec.rb:243:in `block (6 levels) in <top (required)>'
```
Need to update these specs so they are less dependent on the order of the objects created in comparison to the source JSON.

**Comment by ebenenglish** [comment]
Fixed via #15
